stages:
  prepare:
    cmd: python3 src/data/make_dataset.py ./data/raw/
    deps:
    - data/raw/winequality-red.csv
    - src/data/make_dataset.py
  train:
    cmd: python3 src/models/train_model.py, dvc plots show
    deps:
    - src/models/train_model.py
    outs:
    - models/model.h5
    - reports/metrics.png
    metrics:
    - reports/metrics.json:
        cache: false
  predict:
    cmd: python3 src/models/predict_model.py
    deps:
    - src/models/predict_model.py
