name: Red Wine Quality Prediction
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: CML_Train
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          pip install -e .
          
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add report 
          cml-publish reports/metrics.png --md >> report.md
          cml-send-comment report.md
