name: Red Wine Quality Prediction
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: permission
        run: git config --global --add safe.directory /__w/redWineQuality/redWineQuality
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md main > report.md
          # Add figure to the report
          echo "## Validating results by region"
          cml-send-comment report.md
